language: go

go:
  - 1.12.x

go_import_path: github.com/devops787/go-docker-ci

sudo: false

env:

branches:
  only:
    - master
    - stable

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - go vet ./...
  - go test -v
  - go test -v -race ./...
  - go build -v ./...

notifications:
  webhooks:
    urls:
      - https://cloud.docker.com/api/build/v1/source/c0116dd5-88ce-431d-9dc2-5ec14276b632/trigger/3dd09442-705f-44c5-b9ef-266c6336940c/call/
    on_success: change
    on_failure: never
    on_start: never